server:
 port: 8081

spring.datasource.url: jdbc:postgresql://localhost:5432/ticket_booking
spring.datasource.username: postgres
spring.datasource.password: 12345

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR





